# Generated by Django 4.2.1 on 2023-05-21 09:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_participants', models.SmallIntegerField(default=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'batches',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('discount_percentage', models.SmallIntegerField()),
                ('archive', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('premium', models.BooleanField(default=False)),
                ('pre_recorded', models.BooleanField(default=False)),
                ('lectures', models.SmallIntegerField()),
                ('class_duration', models.CharField(help_text='please input here in format: hh:mm', max_length=5)),
                ('course_duration', models.SmallIntegerField()),
                ('projects', models.SmallIntegerField()),
                ('mobile_computer', models.BooleanField(default=True)),
                ('certificate', models.BooleanField(default=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('author_name', models.CharField(max_length=50)),
                ('author_message', models.TextField(blank=True, null=True)),
                ('author_photo', models.ImageField(default='default.png', upload_to='course_author_photos')),
                ('thumbnail', models.FileField(upload_to='course_thumbnails')),
                ('demo_video', models.URLField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Week number or Week Name', max_length=50)),
                ('lock', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='courseManagement.course')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('duration', models.DurationField(blank=True, choices=[(datetime.timedelta(seconds=1800), '30 min'), (datetime.timedelta(seconds=3600), '1 Hr'), (datetime.timedelta(seconds=5400), '1 Hr 30 min'), (datetime.timedelta(seconds=7200), '2 Hr'), (datetime.timedelta(seconds=9000), '2 Hr 30 min'), (datetime.timedelta(seconds=10800), '3 Hr')], null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courseManagement.week')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('link', models.URLField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='courseManagement.batch')),
            ],
        ),
        migrations.CreateModel(
            name='BatchJoined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined', to='courseManagement.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined', to='userManagement.student')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courseManagement.course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='batches', to='userManagement.instructor'),
        ),
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='batches', through='courseManagement.BatchJoined', to='userManagement.student'),
        ),
    ]
