# Generated by Django 4.2.1 on 2023-07-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='topic',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
