# Generated by Django 4.2.1 on 2023-07-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0002_timetable_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='topic',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
