# Generated by Django 4.2.1 on 2023-10-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0004_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='week',
            field=models.CharField(choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8')], default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(upload_to='course_notes'),
        ),
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
