# Generated by Django 4.2.3 on 2023-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0005_note_week_alter_note_file_alter_note_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='week',
            field=models.CharField(blank=True, choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8')], max_length=1, null=True),
        ),
    ]
