# Generated by Django 5.0 on 2024-01-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0006_timetable_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(blank=True, choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='day',
            field=models.CharField(blank=True, choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='week',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
