# Generated by Django 4.2.3 on 2024-01-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0007_timetable_day_timetable_end_time_topic_day_week_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_topic', models.TextField(blank=True, null=True)),
                ('project_name', models.ManyToManyField(blank=True, help_text='After each eg press enter twice to create new project', null=True, to='courseManagement.projectname')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='project_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.projecttopic'),
        ),
        migrations.AddField(
            model_name='batchjoined',
            name='assign_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.projectname'),
        ),
        migrations.AddField(
            model_name='batchjoined',
            name='assign_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.projecttopic'),
        ),
    ]
