# Generated by Django 5.0 on 2024-01-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0008_projectname_projecttopic_batch_project_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttopic',
            name='project_name',
            field=models.ManyToManyField(help_text='After each eg press enter twice to create new project', to='courseManagement.projectname'),
        ),
    ]
