# Generated by Django 4.2.6 on 2024-02-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0009_alter_projecttopic_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='b_certificate',
            field=models.BooleanField(default=False, verbose_name='Batch Certificate Release'),
        ),
        migrations.AddField(
            model_name='batch',
            name='revoke_date',
            field=models.DateField(blank=True, null=True, verbose_name='Batch Revoke Date'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Batch Completed'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Batch End Date'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Batch Start Date'),
        ),
    ]
