# Generated by Django 5.0.1 on 2024-02-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0010_batch_b_certificate_batch_revoke_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='week',
            field=models.CharField(choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8')], max_length=1, null=True),
        ),
    ]
