# Generated by Django 5.0.6 on 2024-06-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0012_alter_note_week_alter_timetable_week_alter_topic_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='project_topic',
        ),
        migrations.RemoveField(
            model_name='batchjoined',
            name='assign_project',
        ),
        migrations.RemoveField(
            model_name='batchjoined',
            name='assign_topic',
        ),
        migrations.AddField(
            model_name='batch',
            name='project_topics',
            field=models.ManyToManyField(blank=True, to='courseManagement.projecttopic'),
        ),
        migrations.AddField(
            model_name='batchjoined',
            name='assign_projects',
            field=models.ManyToManyField(blank=True, to='courseManagement.projectname'),
        ),
        migrations.AddField(
            model_name='batchjoined',
            name='assign_topics',
            field=models.ManyToManyField(blank=True, to='courseManagement.projecttopic'),
        ),
    ]
