# Generated by Django 4.2.6 on 2024-06-11 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0009_alter_student_phone_num'),
        ('courseManagement', '0013_remove_batch_project_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjoined',
            name='full_payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batchjoined',
            name='total_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchjoined',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_students', to='courseManagement.batch'),
        ),
        migrations.AlterField(
            model_name='batchjoined',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_batches', to='userManagement.student'),
        ),
        migrations.CreateModel(
            name='StudentEmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('emi_number', models.IntegerField()),
                ('payment_id', models.CharField(max_length=100)),
                ('payment_status', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_students', to='courseManagement.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_students', to='userManagement.student')),
            ],
        ),
    ]
