# Generated by Django 4.2.6 on 2024-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0014_batchjoined_full_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='revoke_date',
            field=models.IntegerField(blank=True, help_text='input count as day', null=True),
        ),
    ]
