# Generated by Django 4.2.6 on 2024-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0015_alter_batch_revoke_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='revoke_days',
            field=models.IntegerField(blank=True, help_text='input count as day', null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='revoke_date',
            field=models.DateField(blank=True, null=True, verbose_name='Batch Revoke Date'),
        ),
    ]
