# Generated by Django 4.2.6 on 2024-06-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0016_batch_revoke_days_alter_batch_revoke_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmiDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emi_type', models.TextField()),
                ('instament_number', models.IntegerField()),
                ('total_payment', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couser_related_emi', to='courseManagement.course')),
            ],
        ),
        migrations.AddField(
            model_name='studentemi',
            name='payment_mode',
            field=models.CharField(choices=[('', ''), ('manual_entry', 'manual_entry'), ('online_entry', 'online_entry')], default='', max_length=15),
        ),
        migrations.CreateModel(
            name='InstamentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalment', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('emi_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseManagement.emidetails')),
            ],
        ),
    ]
