# Generated by Django 4.2.6 on 2024-06-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0017_emidetails_studentemi_payment_mode_instamentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjoined',
            name='choice_emi_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.emidetails'),
        ),
    ]
