# Generated by Django 4.2.6 on 2024-06-15 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0018_batchjoined_choice_emi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchjoined',
            name='choice_emi_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.emidetails'),
        ),
    ]
