# Generated by Django 4.2.6 on 2024-06-16 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0019_alter_batchjoined_choice_emi_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentemi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentemi',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
