# Generated by Django 4.2.6 on 2024-06-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0020_studentemi_created_at_studentemi_payment_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courseManagement.course')),
            ],
        ),
    ]
