# Generated by Django 4.2.6 on 2024-06-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0021_courseadvantage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseadvantage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='courseManagement.course'),
        ),
    ]
