# Generated by Django 4.2.6 on 2024-06-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0022_alter_courseadvantage_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseAdvantage',
        ),
    ]
