# Generated by Django 4.2.6 on 2024-06-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0024_coursetopic_courseadvantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_duration_in_months',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
