# Generated by Django 4.2.6 on 2024-06-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0025_course_course_duration_in_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIncludeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_includes_topic', to='courseManagement.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_includes', to='courseManagement.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_caption', to='courseManagement.course')),
            ],
        ),
    ]
