# Generated by Django 4.2.6 on 2024-06-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0026_courseincludetopic_courseinclude_coursecaption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinclude',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='courseManagement.course'),
        ),
        migrations.AlterField(
            model_name='courseincludetopic',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='courseManagement.course'),
        ),
    ]
