# Generated by Django 4.2.6 on 2024-06-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0027_alter_courseinclude_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emidetails',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_details', to='courseManagement.course'),
        ),
        migrations.AlterField(
            model_name='instamentdetails',
            name='emi_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emi_variation', to='courseManagement.emidetails'),
        ),
    ]
