# Generated by Django 4.2.6 on 2024-08-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0028_alter_emidetails_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentemi',
            name='json_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentemi',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
