# Generated by Django 4.2.6 on 2024-08-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0029_studentemi_json_response_alter_studentemi_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='instamentdetails',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
