# Generated by Django 4.2.6 on 2024-08-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0030_instamentdetails_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emidetails',
            name='emi_duration',
            field=models.IntegerField(blank=True, help_text='Enter the duration between two EMIs in days', null=True),
        ),
    ]
