# Generated by Django 4.2.6 on 2024-08-30 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0012_remove_notification_read_status_and_more'),
        ('courseManagement', '0031_emidetails_emi_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmiReminderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('emi_number', models.IntegerField(blank=True, null=True)),
                ('emi_amount', models.IntegerField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_emi', to='courseManagement.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_user', to='userManagement.student')),
            ],
        ),
    ]
