# Generated by Django 4.2.6 on 2024-09-01 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0032_emireminderstatuslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='emireminderstatuslog',
            name='reminder_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
