# Generated by Django 4.2.6 on 2024-09-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0033_emireminderstatuslog_reminder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentemi',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
