# Generated by Django 4.2.6 on 2024-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0034_studentemi_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='eligibility',
            field=models.TextField(blank=True, null=True),
        ),
    ]
