# Generated by Django 4.2.6 on 2024-09-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0035_course_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
