# Generated by Django 4.2.6 on 2024-09-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0036_course_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='revoke_duration_in_days',
            field=models.IntegerField(blank=True, help_text='input count as day', null=True),
        ),
    ]
