# Generated by Django 4.2.6 on 2024-09-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0037_course_revoke_duration_in_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_count',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
