# Generated by Django 4.2.6 on 2024-09-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0038_course_certificate_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
