# Generated by Django 4.2.1 on 2023-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('subtext', models.CharField(max_length=50)),
                ('maintext', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='mentors')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('text', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('photo', models.ImageField(upload_to='testimonials')),
                ('stars', models.CharField(choices=[('0', '0 Stars'), ('1', '0.5 Stars'), ('2', '1 Star'), ('3', '1.5 Stars'), ('4', '2 Stars'), ('5', '2.5 Stars'), ('5', '2.5 Stars'), ('6', '3 Stars'), ('7', '3.5 Stars'), ('8', '4 Stars'), ('9', '4.5 Stars'), ('10', '5 Stars')], max_length=2)),
            ],
        ),
    ]
