# Generated by Django 4.2.1 on 2023-05-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0002_rename_mentors_mentor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
