# Generated by Django 4.2.1 on 2023-06-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0004_blog_date_blog_photo_blog_text_blog_title_blogtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
