# Generated by Django 4.2.1 on 2023-06-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0005_blog_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.CharField(default='5', max_length=5),
            preserve_default=False,
        ),
    ]
