# Generated by Django 4.2.1 on 2023-06-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0007_alter_blog_read_time_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
