# Generated by Django 4.2.1 on 2023-06-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0008_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtopic',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='newWebsiteManagement.blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='newWebsiteManagement.blog'),
        ),
    ]
