# Generated by Django 4.2.6 on 2024-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0010_gropuofblog_blog_introduction_blog_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='admin_aproval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
