# Generated by Django 4.2.6 on 2024-06-27 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0011_comment_admin_aproval_comment_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='group_of_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='newWebsiteManagement.gropuofblog'),
        ),
    ]
