# Generated by Django 4.2.6 on 2024-06-28 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0012_alter_blog_group_of_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='admin_aproval',
            new_name='admin_approval',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
