# Generated by Django 4.2.6 on 2024-06-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0013_rename_admin_aproval_comment_admin_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='written_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
