# Generated by Django 4.2.6 on 2024-06-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0014_alter_blog_written_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='written_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
