# Generated by Django 4.2.6 on 2024-08-21 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0015_alter_blog_written_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOfFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='faq',
            name='group_of_faq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='newWebsiteManagement.groupoffaq'),
        ),
    ]
