# Generated by Django 4.2.6 on 2024-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0016_groupoffaq_faq_group_of_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='MediaCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media_coverage/')),
                ('news_link', models.URLField()),
                ('media_logo', models.ImageField(blank=True, null=True, upload_to='media_coverage/')),
            ],
        ),
        migrations.CreateModel(
            name='PlacementStoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_and_role', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to='placement_stories/comments/')),
                ('linked_in_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacementStoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_and_role', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.ImageField(upload_to='placement_story/videos/')),
                ('video_link', models.FileField(upload_to='placement_story/videos/')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='testimonial',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
