# Generated by Django 4.2.6 on 2024-09-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newWebsiteManagement', '0017_gallery_mediacoverage_placementstorycomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
