# Generated by Django 4.2.6 on 2024-01-19 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseManagement', '0009_alter_projecttopic_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8')], max_length=1)),
                ('day', models.CharField(choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3')], max_length=1)),
                ('topic', models.CharField(blank=True, max_length=128, null=True)),
                ('file', models.FileField(upload_to='upload_task')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.course')),
            ],
        ),
    ]
