# Generated by Django 4.2.6 on 2024-02-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0010_batch_b_certificate_batch_revoke_date_and_more'),
        ('userManagement', '0008_instructor_page_visit_count'),
        ('mentorManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchCompleteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('is_certificate', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseManagement.batch')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.instructor')),
            ],
        ),
    ]
