# Generated by Django 5.0.1 on 2024-05-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorManagement', '0003_alter_syllabus_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='file',
            field=models.FileField(blank=True, upload_to='upload_task'),
        ),
    ]
