# Generated by Django 4.2.6 on 2024-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0015_alter_batch_revoke_date'),
        ('mentorManagement', '0004_syllabus_description_alter_syllabus_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchcompleterequest',
            name='is_certificate',
        ),
        migrations.AddField(
            model_name='batchcompleterequest',
            name='certified_students',
            field=models.ManyToManyField(blank=True, related_name='certified_requests', to='courseManagement.batchjoined'),
        ),
    ]
