# Generated by Django 4.2.6 on 2024-06-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorManagement', '0005_remove_batchcompleterequest_is_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchcompleterequest',
            name='certified_students',
        ),
    ]
