# Generated by Django 4.2.6 on 2024-06-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentorManagement', '0006_remove_batchcompleterequest_certified_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchcompleterequest',
            name='send_email_for_certification',
            field=models.BooleanField(default=False),
        ),
    ]
