# Generated by Django 4.2.1 on 2023-08-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='status',
            field=models.CharField(choices=[('0', 'Not Contacted'), ('1', 'Not Answered'), ('2', 'Follow Up'), ('3', 'Not Interested'), ('4', 'Converted')], default='0', max_length=1),
        ),
    ]
