# Generated by Django 4.2.1 on 2023-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_alter_contactinfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='assigned_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
