# Generated by Django 4.2.6 on 2024-09-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_contactinfo_assigned_date_contactinfo_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
