# Generated by Django 4.2.1 on 2023-07-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sales-person-photo'),
        ),
    ]
