# Generated by Django 4.2.3 on 2023-12-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_alter_salesperson_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
    ]
