# Generated by Django 4.2.6 on 2024-01-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_notificationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='terms_condition',
            field=models.BooleanField(default=False),
        ),
    ]
