# Generated by Django 4.2.6 on 2024-01-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0005_student_terms_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='rules_regulation_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='instructor',
            name='terms_condition',
            field=models.BooleanField(default=False),
        ),
    ]
