# Generated by Django 4.2.6 on 2024-01-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_instructor_rules_regulation_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='rules_regulation_count',
            field=models.IntegerField(default=0),
        ),
    ]
