# Generated by Django 4.2.6 on 2024-02-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0007_alter_instructor_rules_regulation_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='page_visit_count',
            field=models.IntegerField(default=0),
        ),
    ]
