# Generated by Django 5.0.1 on 2024-05-17 19:56

import userManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0008_instructor_page_visit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=models.CharField(blank=True, help_text='max length is 10', max_length=10, null=True, validators=[userManagement.models.validate_phone_number], verbose_name='Phone Number'),
        ),
    ]
