# Generated by Django 4.2.6 on 2024-08-09 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManagement', '0009_alter_student_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('notify_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_status', models.ManyToManyField(blank=True, related_name='read_notifications', to='userManagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('notify_text', models.TextField(blank=True, null=True)),
                ('read_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roomUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notice',
            name='read_status',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NotificationStatus',
        ),
        migrations.AddField(
            model_name='notificationbox',
            name='noti_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.notificationroom'),
        ),
        migrations.AddField(
            model_name='notification',
            name='room',
            field=models.ManyToManyField(blank=True, to='userManagement.notificationroom'),
        ),
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='userManagement.student'),
        ),
    ]
