# Generated by Django 4.2.6 on 2024-08-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0011_studentpersonaldetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read_status',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='room',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
        migrations.RemoveField(
            model_name='notificationbox',
            name='noti_room',
        ),
        migrations.RemoveField(
            model_name='notificationroom',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='NotificationBox',
        ),
        migrations.DeleteModel(
            name='NotificationRoom',
        ),
    ]
