# Generated by Django 4.2.6 on 2024-09-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0012_remove_notification_read_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentpersonaldetails',
            old_name='year',
            new_name='role',
        ),
    ]
