# Generated by Django 4.2.6 on 2024-09-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0014_subadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmin',
            name='otp',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='otp_validation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='password_raw',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
