# Generated by Django 4.2.6 on 2024-09-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0015_subadmin_otp_subadmin_otp_validation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subadmin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
