# Generated by Django 4.2.6 on 2024-09-06 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManagement', '0016_subadmin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_num', models.CharField(help_text='max length is 10', max_length=10, verbose_name='Phone Number')),
                ('location', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sales-person-photo')),
                ('otp', models.SmallIntegerField(blank=True, editable=False, null=True)),
                ('password_raw', models.CharField(blank=True, max_length=15, null=True)),
                ('otp_validation_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
