# Generated by Django 4.2.6 on 2024-09-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0017_dataentryuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentryuser',
            name='otp',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='otp',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
