# Generated by Django 4.2.6 on 2024-09-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0018_alter_dataentryuser_otp_alter_subadmin_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='instructor-signatures'),
        ),
    ]
