# Generated by Django 4.2.6 on 2024-09-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0020_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
