# Generated by Django 4.2.6 on 2024-09-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0021_student_otp_student_otp_expiry_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='otp',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='otp_validation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='password_raw',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
