# Generated by Django 4.2.6 on 2024-09-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0022_salesperson_otp_salesperson_otp_validation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
