# Generated by Django 4.2.6 on 2024-09-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0023_salesperson_area_salesperson_branch_salesperson_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='password_raw',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
