# Generated by Django 4.2.6 on 2024-09-21 17:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userManagement', '0024_instructor_email_instructor_password_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentryuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='data-entry-user-photo'),
        ),
        migrations.AlterField(
            model_name='subadmin',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sub-admin-photo'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('Rent', 'Rent'), ('Salary', 'Salary'), ('Freelancer', 'Freelancer'), ('Insta Marketing', 'Insta Marketing'), ('Tech Related', 'Tech Related'), ('Others', 'Others')], max_length=25)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expense-receipt')),
                ('mode', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
