# Generated by Django 4.2.6 on 2024-09-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0025_alter_dataentryuser_photo_alter_subadmin_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='mode',
            field=models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='offline', max_length=25),
        ),
    ]
