# Generated by Django 4.2.6 on 2024-09-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0028_expense_to_user_details_alter_expense_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='to_user_type',
            field=models.CharField(blank=True, choices=[('sub_admin', 'Sub Admin'), ('mentor', 'Mentor'), ('data_entry', 'Data Entry'), ('sales', 'Sales'), ('rent', 'Rent')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='user_type',
            field=models.CharField(choices=[('sub_admin', 'Sub Admin'), ('mentor', 'Mentor'), ('data_entry', 'Data Entry'), ('sales', 'Sales'), ('rent', 'Rent')], max_length=20),
        ),
    ]
