# Generated by Django 4.2.6 on 2024-09-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0029_alter_expense_to_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentryuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salesperson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='to_user_type',
            field=models.CharField(blank=True, choices=[('sub_admin', 'Sub Admin'), ('mentor', 'Mentor'), ('data_entry', 'Data Entry'), ('sales', 'Sales')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='user_type',
            field=models.CharField(choices=[('sub_admin', 'Sub Admin'), ('mentor', 'Mentor'), ('data_entry', 'Data Entry'), ('sales', 'Sales')], max_length=20),
        ),
    ]
