# Generated by Django 4.2.6 on 2024-09-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0030_dataentryuser_is_active_instructor_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
