# Generated by Django 4.2.6 on 2024-09-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0031_alter_expense_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
