# Generated by Django 4.2.6 on 2024-07-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0009_alter_student_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=100)),
                ('archive', models.BooleanField(default=False)),
                ('popular', models.BooleanField(default=False)),
                ('pre_recorded', models.BooleanField(default=False)),
                ('course_duration_title', models.CharField(blank=True, max_length=255, null=True)),
                ('projects', models.SmallIntegerField()),
                ('section_number', models.PositiveIntegerField(editable=False)),
                ('mobile_computer', models.BooleanField(default=True)),
                ('certificate', models.BooleanField(default=True)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('author_name', models.CharField(max_length=50)),
                ('author_message', models.TextField(blank=True, null=True)),
                ('author_photo', models.ImageField(default='default.png', upload_to='free_course_author_photos')),
                ('thumbnail', models.FileField(upload_to='free_course_thumbnails')),
                ('demo_video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FreeCourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False)),
                ('name', models.CharField(max_length=255)),
                ('max_attempts', models.PositiveIntegerField(default=50, help_text='Maximum number of time a student can attempt the questions.')),
                ('max_score', models.FloatField(default=75.0, help_text='Minimum passing percentage')),
                ('time_duration', models.DurationField(blank=True, null=True)),
                ('number_of_questions', models.PositiveIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_syllabus', to='freeCourseManagement.freecourse')),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='free_course_syllabus')),
                ('video', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_topics', to='freeCourseManagement.freecoursesyllabus')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestionAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('attempt_answer', models.JSONField(blank=True, null=True)),
                ('attempt_score', models.FloatField(blank=True, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('right_answers', models.PositiveIntegerField(blank=True, help_text='Number of right answers..', null=True)),
                ('wrong_answers', models.PositiveIntegerField(blank=True, help_text='Number of wrong answers..', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_questions', to='freeCourseManagement.freecourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_student', to='userManagement.student')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_questions', to='freeCourseManagement.freecoursesyllabus')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option1', models.TextField(blank=True, null=True)),
                ('option2', models.TextField(blank=True, null=True)),
                ('option3', models.TextField(blank=True, null=True)),
                ('option4', models.TextField(blank=True, null=True)),
                ('answer', models.CharField(blank=True, choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=10, null=True)),
                ('course_section_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='freeCourseManagement.coursesectionquestion')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_topic', to='freeCourseManagement.syllabustopics')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCourseJoinee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(blank=True, default=False)),
                ('is_certificate', models.BooleanField(blank=True, default=False)),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freeCourseManagement.freecourse')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCourseIncludeTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_course_topics', to='freeCourseManagement.freecourse')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCourseInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_course_includes', to='freeCourseManagement.freecourse')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCourseCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_course_caption', to='freeCourseManagement.freecourse')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCourseAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_course_advantages', to='freeCourseManagement.freecourse')),
            ],
        ),
        migrations.AddField(
            model_name='coursesectionquestion',
            name='course_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeCourseManagement.freecoursesyllabus'),
        ),
    ]
