# Generated by Django 4.2.6 on 2024-07-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0002_freecoursecompilerquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='prob_id',
        ),
        migrations.AlterField(
            model_name='freecoursecompilerquestion',
            name='const_pic',
            field=models.ImageField(blank=True, null=True, upload_to='free_course_constraints_pictures'),
        ),
        migrations.AlterField(
            model_name='freecoursecompilerquestion',
            name='example1_picture',
            field=models.ImageField(blank=True, null=True, upload_to='free_course_example1_pictures/'),
        ),
        migrations.AlterField(
            model_name='freecoursecompilerquestion',
            name='example2_picture',
            field=models.ImageField(blank=True, null=True, upload_to='free_course_example2_pictures/'),
        ),
        migrations.AlterField(
            model_name='freecoursecompilerquestion',
            name='example3_picture',
            field=models.ImageField(blank=True, null=True, upload_to='free_course_example3_pictures/'),
        ),
        migrations.AlterField(
            model_name='freecoursecompilerquestion',
            name='prob_pic',
            field=models.ImageField(blank=True, null=True, upload_to='free_course_quesion_pictures'),
        ),
        migrations.AlterField(
            model_name='freecoursecompilerquestionapproachcode',
            name='approach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_question_approach_code', to='freeCourseManagement.freecoursecompilerquestionapproach'),
        ),
        migrations.AlterField(
            model_name='freecoursecompilerquestionapproachimage',
            name='approach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_question_approach_image', to='freeCourseManagement.freecoursecompilerquestionapproach'),
        ),
        migrations.AlterField(
            model_name='freecoursecompilerquestionapproachimage',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='free_course_approach_pictures', verbose_name='Pic '),
        ),
    ]
