# Generated by Django 4.2.6 on 2024-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0009_alter_student_phone_num'),
        ('freeCourseManagement', '0003_remove_freecoursecompilerquestion_prob_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecoursecompilerquestion',
            name='students',
            field=models.ManyToManyField(blank=True, to='userManagement.student'),
        ),
    ]
