# Generated by Django 4.2.6 on 2024-07-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0004_alter_freecoursecompilerquestion_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecoursecompilerquestionapproach',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_course_compiler_question_approach', to='freeCourseManagement.freecoursecompilerquestion'),
        ),
    ]
