# Generated by Django 4.2.6 on 2024-07-19 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0005_alter_freecoursecompilerquestionapproach_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='day',
        ),
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='week',
        ),
    ]
