# Generated by Django 4.2.6 on 2024-07-19 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0009_alter_student_phone_num'),
        ('freeCourseManagement', '0006_remove_freecoursecompilerquestion_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freecoursesyllabus',
            old_name='max_attempts',
            new_name='max_attempts_mock',
        ),
        migrations.RenameField(
            model_name='freecoursesyllabus',
            old_name='max_score',
            new_name='max_score_mock',
        ),
        migrations.RenameField(
            model_name='freecoursesyllabus',
            old_name='time_duration',
            new_name='time_duration_mock',
        ),
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='check_exm_pic1',
        ),
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='check_exm_pic2',
        ),
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='check_exm_pic3',
        ),
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='course',
        ),
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='example1_picture',
        ),
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='example2_picture',
        ),
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='example3_picture',
        ),
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='students',
        ),
        migrations.AddField(
            model_name='freecoursecompilerquestion',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compiler_question_topic', to='freeCourseManagement.syllabustopics'),
        ),
        migrations.AddField(
            model_name='freecoursesyllabus',
            name='max_attempts_practice',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of time a student can attempt the questions.'),
        ),
        migrations.AddField(
            model_name='freecoursesyllabus',
            name='max_attempts_quiz',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of time a student can attempt the questions.'),
        ),
        migrations.AddField(
            model_name='freecoursesyllabus',
            name='max_score_practice',
            field=models.FloatField(default=75.0, help_text='Minimum passing percentage'),
        ),
        migrations.AddField(
            model_name='freecoursesyllabus',
            name='max_score_quiz',
            field=models.FloatField(default=75.0, help_text='Minimum passing percentage'),
        ),
        migrations.AddField(
            model_name='freecoursesyllabus',
            name='time_duration_practice',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freecoursesyllabus',
            name='time_duration_quiz',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FreeCourseCompilerQuestionLoadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_template', models.TextField(blank=True, null=True)),
                ('compiler', models.CharField(blank=True, choices=[('Assembly (NASM 2.14.02) || 45', 'Assembly (NASM 2.14.02) || 45'), ('Bash (5.0.0) || 46', 'Bash (5.0.0) || 46'), ('Basic (FBC 1.07.1) || 47', 'Basic (FBC 1.07.1) || 47'), ('C (Clang 7.0.1) || 75', 'C (Clang 7.0.1) || 75'), ('C++ (Clang 7.0.1) || 76', 'C++ (Clang 7.0.1) || 76'), ('C (GCC 7.4.0) || 48', 'C (GCC 7.4.0) || 48'), ('C++ (GCC 7.4.0) || 52', 'C++ (GCC 7.4.0) || 52'), ('C (GCC 8.3.0) || 49', 'C (GCC 8.3.0) || 49'), ('C++ (GCC 8.3.0) || 53', 'C++ (GCC 8.3.0) || 53'), ('C (GCC 9.2.0) || 50', 'C (GCC 9.2.0) || 50'), ('C++ (GCC 9.2.0) || 54', 'C++ (GCC 9.2.0) || 54'), ('Clojure (1.10.1) || 86', 'Clojure (1.10.1) || 86'), ('C# (Mono 6.6.0.161) || 51', 'C# (Mono 6.6.0.161) || 51'), ('COBOL (GnuCOBOL 2.2) || 77', 'COBOL (GnuCOBOL 2.2) || 77'), ('Common Lisp (SBCL 2.0.0) || 55', 'Common Lisp (SBCL 2.0.0) || 55'), ('Dart (2.19.2) || 90', 'Dart (2.19.2) || 90'), ('D (DMD 2.089.1) || 56', 'D (DMD 2.089.1) || 56'), ('Elixir (1.9.4) || 57', 'Elixir (1.9.4) || 57'), ('Erlang (OTP 22.2) || 58', 'Erlang (OTP 22.2) || 58'), ('Executable || 44', 'Executable || 44'), ('F# (.NET Core SDK 3.1.202) || 87', 'F# (.NET Core SDK 3.1.202) || 87'), ('Fortran (GFortran 9.2.0) || 59', 'Fortran (GFortran 9.2.0) || 59'), ('Go (1.13.5) || 60', 'Go (1.13.5) || 60'), ('Go (1.18.5) || 95', 'Go (1.18.5) || 95'), ('Groovy (3.0.3) || 88', 'Groovy (3.0.3) || 88'), ('Haskell (GHC 8.8.1) || 61', 'Haskell (GHC 8.8.1) || 61'), ('Java (JDK 17.0.6) || 91', 'Java (JDK 17.0.6) || 91'), ('Java (OpenJDK 13.0.1) || 62', 'Java (OpenJDK 13.0.1) || 62'), ('JavaScript (Node.js 12.14.0) || 63', 'JavaScript (Node.js 12.14.0) || 63'), ('JavaScript (Node.js 18.15.0) || 93', 'JavaScript (Node.js 18.15.0) || 93'), ('Kotlin (1.3.70) || 78', 'Kotlin (1.3.70) || 78'), ('Lua (5.3.5) || 64', 'Lua (5.3.5) || 64'), ('Multi-file program || 89', 'Multi-file program || 89'), ('Objective-C (Clang 7.0.1) || 79', 'Objective-C (Clang 7.0.1) || 79'), ('OCaml (4.09.0) || 65', 'OCaml (4.09.0) || 65'), ('Octave (5.1.0) || 66', 'Octave (5.1.0) || 66'), ('Pascal (FPC 3.0.4) || 67', 'Pascal (FPC 3.0.4) || 67'), ('Perl (5.28.1) || 85', 'Perl (5.28.1) || 85'), ('PHP (7.4.1) || 68', 'PHP (7.4.1) || 68'), ('Plain Text || 43', 'Plain Text || 43'), ('Prolog (GNU Prolog 1.4.5) || 69', 'Prolog (GNU Prolog 1.4.5) || 69'), ('Python (2.7.17) || 70', 'Python (2.7.17) || 70'), ('Python (3.11.2) || 92', 'Python (3.11.2) || 92'), ('Python (3.8.1) || 71', 'Python (3.8.1) || 71'), ('R (4.0.0) || 80', 'R (4.0.0) || 80'), ('Ruby (2.7.0) || 72', 'Ruby (2.7.0) || 72'), ('Rust (1.40.0) || 73', 'Rust (1.40.0) || 73'), ('Scala (2.13.2) || 81', 'Scala (2.13.2) || 81'), ('SQL (SQLite 3.27.2) || 82', 'SQL (SQLite 3.27.2) || 82'), ('Swift (5.2.3) || 83', 'Swift (5.2.3) || 83'), ('TypeScript (3.7.4) || 74', 'TypeScript (3.7.4) || 74'), ('TypeScript (5.0.3) || 94', 'TypeScript (5.0.3) || 94'), ('Visual Basic.Net (vbnc 0.0.0.5943) || 84', 'Visual Basic.Net (vbnc 0.0.0.5943) || 84')], max_length=255, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_course_com_ques', to='freeCourseManagement.freecoursecompilerquestion')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCourseCompilerQuestionExampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_picture', models.ImageField(blank=True, null=True, upload_to='free_course_example_pictures/')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='free_course_com_ques_ex_image', to='freeCourseManagement.freecoursecompilerquestion')),
            ],
        ),
        migrations.CreateModel(
            name='FreeCourseCompilerQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('attepmt_number', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('coding_language', models.CharField(blank=True, help_text='Language', max_length=255, null=True)),
                ('student_ans', models.TextField(blank=True, help_text='Student Code', null=True)),
                ('code_response_status', models.JSONField(blank=True, default=dict, null=True)),
                ('code_response', models.TextField(blank=True, help_text='Response from judge0', null=True)),
                ('button_clicked', models.CharField(blank=True, choices=[('Run', 'Run'), ('Submit', 'Submit')], max_length=11, null=True)),
                ('score', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('practic_time', models.DateTimeField(auto_now=True)),
                ('max_attempt_number', models.PositiveBigIntegerField(null=True)),
                ('load_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_ques_template', to='freeCourseManagement.freecoursecompilerquestionloadtemplate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_ques', to='freeCourseManagement.freecoursecompilerquestion')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempting_student', to='userManagement.student')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSyllabusCompilerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freeCourseManagement.freecoursesyllabus')),
            ],
        ),
        migrations.AddField(
            model_name='freecoursecompilerquestion',
            name='course_section_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compiler_questions', to='freeCourseManagement.coursesyllabuscompilerquestion'),
            preserve_default=False,
        ),
    ]
