# Generated by Django 4.2.6 on 2024-07-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0007_rename_max_attempts_freecoursesyllabus_max_attempts_mock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecoursecompilerquestion',
            name='course_section_question',
        ),
        migrations.AddField(
            model_name='freecoursecompilerquestion',
            name='course_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compiler_questions', to='freeCourseManagement.freecoursesyllabus'),
        ),
        migrations.DeleteModel(
            name='CourseSyllabusCompilerQuestion',
        ),
    ]
