# Generated by Django 4.2.6 on 2024-07-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0008_remove_freecoursecompilerquestion_course_section_question_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesectionquestion',
            options={'verbose_name': 'Course Syllabus', 'verbose_name_plural': 'Section Quiz Questions'},
        ),
        migrations.RenameField(
            model_name='freecoursesyllabus',
            old_name='max_attempts_quiz',
            new_name='max_attempts',
        ),
        migrations.RenameField(
            model_name='freecoursesyllabus',
            old_name='max_score_quiz',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='freecoursesyllabus',
            old_name='time_duration_quiz',
            new_name='time_duration',
        ),
    ]
