# Generated by Django 4.2.6 on 2024-07-20 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0009_alter_coursesectionquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecoursecompilerquestionattempt',
            name='max_attempt_number',
        ),
        migrations.AddField(
            model_name='freecoursecompilerquestionattempt',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_compiler_questions', to='freeCourseManagement.freecourse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='freecoursecompilerquestionattempt',
            name='syllabus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_compiler_questions', to='freeCourseManagement.freecoursesyllabus'),
            preserve_default=False,
        ),
    ]
