# Generated by Django 4.2.6 on 2024-07-21 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0009_alter_student_phone_num'),
        ('freeCourseManagement', '0010_remove_freecoursecompilerquestionattempt_max_attempt_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePracticeCompilerQuestionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.TextField()),
                ('autosave_time', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.student')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_template', to='freeCourseManagement.freecoursecompilerquestionloadtemplate')),
            ],
        ),
    ]
