# Generated by Django 4.2.6 on 2024-07-22 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0011_savepracticecompilerquestioncode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecoursesyllabus',
            name='max_attempts_practice',
        ),
        migrations.RemoveField(
            model_name='freecoursesyllabus',
            name='max_score_practice',
        ),
        migrations.RemoveField(
            model_name='freecoursesyllabus',
            name='time_duration_practice',
        ),
    ]
