# Generated by Django 4.2.6 on 2024-07-23 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0009_alter_student_phone_num'),
        ('freeCourseManagement', '0012_remove_freecoursesyllabus_max_attempts_practice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockCompilerQuestionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(blank=True, null=True)),
                ('attempt_number', models.IntegerField()),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('right_answers', models.PositiveIntegerField(blank=True, help_text='Number of right answers..', null=True)),
                ('wrong_answers', models.PositiveIntegerField(blank=True, help_text='Number of wrong answers..', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_mock_question_result', to='freeCourseManagement.freecourse')),
                ('course_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_mock_result', to='freeCourseManagement.freecoursesyllabus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mock_result', to='userManagement.student')),
            ],
        ),
    ]
