# Generated by Django 4.2.6 on 2024-07-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0013_mockcompilerquestionresult'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuizQuestion',
            new_name='FreeCourseQuizQuestion',
        ),
    ]
