# Generated by Django 4.2.6 on 2024-07-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0014_rename_quizquestion_freecoursequizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecoursesyllabus',
            name='max_score_practice',
            field=models.FloatField(default=75.0, help_text='Minimum passing percentage'),
        ),
    ]
