# Generated by Django 4.2.6 on 2024-07-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0009_alter_student_phone_num'),
        ('freeCourseManagement', '0015_freecoursesyllabus_max_score_practice'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecourse',
            name='average_mock_score',
            field=models.FloatField(default=75.0, help_text='Minimum average mock score for certificate.'),
        ),
        migrations.AddField(
            model_name='freecourse',
            name='average_practice_score',
            field=models.FloatField(default=75.0, help_text='Minimum average practice score for certificate.'),
        ),
        migrations.AddField(
            model_name='freecourse',
            name='average_quiz_score',
            field=models.FloatField(default=75.0, help_text='Minimum average quiz score for certificate.'),
        ),
        migrations.AlterUniqueTogether(
            name='freecoursecompilerquestionattempt',
            unique_together={('student', 'question')},
        ),
    ]
