# Generated by Django 4.2.6 on 2024-07-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0016_freecourse_average_mock_score_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='freecoursecompilerquestionattempt',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='freecoursejoinee',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='free_course_certificates'),
        ),
        migrations.AddField(
            model_name='freecoursejoinee',
            name='is_released',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
