# Generated by Django 4.2.6 on 2024-07-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0017_alter_freecoursecompilerquestionattempt_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecoursejoinee',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
    ]
