# Generated by Django 4.2.6 on 2024-08-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0018_alter_freecoursejoinee_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecoursejoinee',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
