# Generated by Django 4.2.6 on 2024-08-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0019_freecoursejoinee_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecoursejoinee',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Course completion date', null=True),
        ),
    ]
