# Generated by Django 4.2.6 on 2024-09-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0020_freecoursejoinee_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecoursecompilerquestion',
            name='test_cases_to_view',
            field=models.JSONField(default=dict),
        ),
    ]
