# Generated by Django 4.2.6 on 2024-09-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0021_freecoursecompilerquestion_test_cases_to_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecoursecompilerquestion',
            name='test_cases_to_view',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
