# Generated by Django 4.2.6 on 2024-09-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0022_alter_freecoursecompilerquestion_test_cases_to_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecourse',
            name='serial_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
