# Generated by Django 4.2.6 on 2024-09-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0023_freecourse_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecoursecompilerquestionexampleimage',
            name='example_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='syllabustopics',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
