# Generated by Django 4.2.6 on 2024-09-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freeCourseManagement', '0024_freecoursecompilerquestionexampleimage_example_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freecourse',
            options={'ordering': ['serial_no']},
        ),
        migrations.AlterModelOptions(
            name='freecoursesyllabus',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='syllabustopics',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='freecourse',
            name='certificate_no',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
