# Generated by Django 4.2.1 on 2023-08-23 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userManagement', '0002_alter_salesperson_photo'),
        ('courseManagement', '0003_alter_timetable_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseManagement.course')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('answers', models.JSONField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsManagement.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.student')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='students',
            field=models.ManyToManyField(through='testsManagement.QuizAttempt', to='userManagement.student'),
        ),
    ]
