# Generated by Django 4.2.1 on 2023-08-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0003_quizquestion_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='week',
            field=models.CharField(choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8')], default='1', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
