# Generated by Django 4.2.1 on 2023-10-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_alter_salesperson_photo'),
        ('testsManagement', '0004_quiz_week_quizattempt_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disable', models.BooleanField(default=False)),
                ('practice_mock', models.BooleanField(default=False, help_text="False is 'Practice Question'; True is 'Mock Test Question'")),
                ('week', models.CharField(choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8')], max_length=1)),
                ('day', models.CharField(choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3')], max_length=1)),
                ('question_number', models.CharField(max_length=2)),
                ('ques_title', models.CharField(max_length=255)),
                ('google', models.BooleanField(default=True)),
                ('amazon', models.BooleanField(default=True)),
                ('microsoft', models.BooleanField(default=True)),
                ('meta', models.BooleanField(default=True)),
                ('linkedin', models.BooleanField(default=True)),
                ('uber', models.BooleanField(default=True)),
                ('adobe', models.BooleanField(default=True)),
                ('cred', models.BooleanField(default=True)),
                ('prob_text', models.TextField()),
                ('ques_pic', models.ImageField(upload_to='quesion_pictures')),
                ('const_pic', models.ImageField(upload_to='constraints_pictures')),
                ('examples', models.TextField(help_text='After each eg press enter twice to create new example')),
                ('hint_video', models.URLField()),
                ('hint_theory', models.TextField()),
                ('hint_pic', models.ImageField(upload_to='hint_pictures')),
                ('hint_code', models.TextField(help_text='After each code press enter twice to create new code hint')),
            ],
        ),
        migrations.CreateModel(
            name='CompilerQuestionAtempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('c', 'C++'), ('j', 'JAVA'), ('p', 'Python')], max_length=1)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('attepmt_number', models.PositiveBigIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsManagement.compilerquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.student')),
            ],
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='students',
            field=models.ManyToManyField(through='testsManagement.CompilerQuestionAtempt', to='userManagement.student'),
        ),
    ]
