# Generated by Django 4.2.1 on 2023-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0005_compilerquestion_compilerquestionatempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilerquestion',
            name='ques_title',
            field=models.CharField(max_length=255, verbose_name='Question Title'),
        ),
    ]
