# Generated by Django 4.2.1 on 2023-10-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0006_alter_compilerquestion_ques_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='score',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
