# Generated by Django 4.2.1 on 2023-10-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0008_alter_quizattempt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='answers',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
