# Generated by Django 4.2.3 on 2023-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0009_alter_quizattempt_answers_alter_quizattempt_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='questions',
            field=models.ManyToManyField(to='testsManagement.quizquestion'),
        ),
    ]
