# Generated by Django 4.2.7 on 2023-12-01 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0006_timetable_week'),
        ('testsManagement', '0010_quizattempt_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_field', models.CharField(blank=True, choices=[('Quiz', 'Quiz'), ('Practice', 'Practice'), ('Mock', 'Mock')], max_length=20, null=True)),
                ('time_for', models.CharField(blank=True, choices=[('Total Time', 'Total Time'), ('Per Question Time', 'Per Question Time')], max_length=20, null=True)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.course'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='prob_id',
            field=models.CharField(blank=True, help_text='Question Id from sphere-engine', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestionatempt',
            name='code_response',
            field=models.TextField(blank=True, help_text='Response from sphere-engine', null=True),
        ),
        migrations.AddField(
            model_name='compilerquestionatempt',
            name='coding_language',
            field=models.CharField(blank=True, help_text='Language', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestionatempt',
            name='student_ans',
            field=models.TextField(blank=True, help_text='Student Code', null=True),
        ),
        migrations.AddField(
            model_name='compilerquestionatempt',
            name='submissions_id',
            field=models.CharField(blank=True, help_text='submissions ID from sphere-engine', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CompilerQuestionLoadTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_template', models.TextField()),
                ('compilers_name', models.CharField(blank=True, help_text='Compilers name from sphere-engine', max_length=255, null=True)),
                ('compilers_id', models.CharField(blank=True, help_text='Compilers ID from sphere-engine', max_length=255, null=True)),
                ('question_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsManagement.compilerquestion')),
            ],
        ),
    ]
