# Generated by Django 4.2.7 on 2023-12-18 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0006_timetable_week'),
        ('userManagement', '0004_notificationstatus'),
        ('testsManagement', '0015_alter_compilerquestionloadtemplate_compiler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mock_unlock_week', models.CharField(blank=True, choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8')], max_length=1, null=True)),
                ('mock', models.BooleanField(default=False)),
                ('current_quiz_unlock_week', models.CharField(blank=True, choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8')], max_length=1, null=True)),
                ('quiz', models.BooleanField(default=False)),
                ('current_practice_unlock_week', models.CharField(blank=True, choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8')], max_length=1, null=True)),
                ('practice', models.BooleanField(default=False)),
                ('message_text', models.TextField()),
                ('message_created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseManagement.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.student')),
            ],
        ),
    ]
