# Generated by Django 4.2.7 on 2023-12-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0016_messagedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagedetails',
            name='message_text',
        ),
        migrations.AddField(
            model_name='messagedetails',
            name='content',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='messagedetails',
            name='title',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
