# Generated by Django 4.2.3 on 2023-12-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0006_timetable_week'),
        ('testsManagement', '0017_remove_messagedetails_message_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilerquestionloadtemplate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.course'),
        ),
        migrations.AddField(
            model_name='questiontimer',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.course'),
        ),
        migrations.AddField(
            model_name='questiontimer',
            name='no_of_questions',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
