# Generated by Django 5.0 on 2023-12-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0018_compilerquestionloadtemplate_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilerquestion',
            name='test_case',
            field=models.TextField(blank=True, default='null', help_text='After each eg press enter twice to create new cases', null=True),
        ),
    ]
