# Generated by Django 5.0 on 2023-12-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0019_compilerquestion_test_case'),
        ('userManagement', '0004_notificationstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavePracticeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsManagement.compilerquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManagement.student')),
            ],
        ),
    ]
