# Generated by Django 5.0 on 2023-12-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0020_savepracticecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilerquestionatempt',
            name='language',
        ),
        migrations.AlterField(
            model_name='compilerquestionatempt',
            name='attepmt_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
