# Generated by Django 4.2.3 on 2023-12-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0021_remove_compilerquestionatempt_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilerquestion',
            name='hint_code',
        ),
        migrations.RemoveField(
            model_name='compilerquestion',
            name='hint_pic',
        ),
        migrations.RemoveField(
            model_name='compilerquestion',
            name='hint_theory',
        ),
        migrations.RemoveField(
            model_name='compilerquestion',
            name='hint_video',
        ),
        migrations.RemoveField(
            model_name='compilerquestion',
            name='ques_pic',
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_algo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_code_implementation',
            field=models.BooleanField(default=False, verbose_name='Approach1 Code Implementation'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_complexity_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_cpp_code',
            field=models.TextField(blank=True, null=True, verbose_name='C++ Code'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_intuition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_java_code',
            field=models.TextField(blank=True, null=True, verbose_name='Java Code'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_pic1',
            field=models.ImageField(blank=True, null=True, upload_to='approach1_pictures', verbose_name='Pic 1'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_pic2',
            field=models.ImageField(blank=True, null=True, upload_to='approach1_pictures', verbose_name='Pic 2'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_pic3',
            field=models.ImageField(blank=True, null=True, upload_to='approach1_pictures', verbose_name='Pic 3'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_pic4',
            field=models.ImageField(blank=True, null=True, upload_to='approach1_pictures', verbose_name='Pic 4'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_pic5',
            field=models.ImageField(blank=True, null=True, upload_to='approach1_pictures', verbose_name='Pic 5'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_picture_implementation',
            field=models.BooleanField(default=False, verbose_name='Approach1 Picture Implementation'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_python_code',
            field=models.TextField(blank=True, null=True, verbose_name='Python Code'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_algo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_code_implementation',
            field=models.BooleanField(default=False, verbose_name='Approach2 Code Implementation'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_complexity_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_cpp_code',
            field=models.TextField(blank=True, null=True, verbose_name='C++ Code '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_intuition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_java_code',
            field=models.TextField(blank=True, null=True, verbose_name='Java Code '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_pic1',
            field=models.ImageField(blank=True, null=True, upload_to='approach2_pictures', verbose_name='Pic 1 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_pic2',
            field=models.ImageField(blank=True, null=True, upload_to='approach2_pictures', verbose_name='Pic 2 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_pic3',
            field=models.ImageField(blank=True, null=True, upload_to='approach2_pictures', verbose_name='Pic 3 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_pic4',
            field=models.ImageField(blank=True, null=True, upload_to='approach2_pictures', verbose_name='Pic 4 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_pic5',
            field=models.ImageField(blank=True, null=True, upload_to='approach2_pictures', verbose_name='Pic 5 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_picture_implementation',
            field=models.BooleanField(default=False, verbose_name='Approach2 Picture Implementation'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_python_code',
            field=models.TextField(blank=True, null=True, verbose_name='Python Code '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach2_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_algo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_block',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_code_implementation',
            field=models.BooleanField(default=False, verbose_name='Approach3 Code Implementation'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_complexity_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_cpp_code',
            field=models.TextField(blank=True, null=True, verbose_name='C++ Code '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_intuition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_java_code',
            field=models.TextField(blank=True, null=True, verbose_name='Java Code '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_pic1',
            field=models.ImageField(blank=True, null=True, upload_to='approach3_pictures', verbose_name='Pic 1 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_pic2',
            field=models.ImageField(blank=True, null=True, upload_to='approach3_pictures', verbose_name='Pic 2 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_pic3',
            field=models.ImageField(blank=True, null=True, upload_to='approach3_pictures', verbose_name='Pic 3 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_pic4',
            field=models.ImageField(blank=True, null=True, upload_to='approach3_pictures', verbose_name='Pic 4 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_pic5',
            field=models.ImageField(blank=True, null=True, upload_to='approach3_pictures', verbose_name='Pic 5 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_picture_implementation',
            field=models.BooleanField(default=False, verbose_name='Approach3 Picture Implementation'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_python_code',
            field=models.TextField(blank=True, null=True, verbose_name='Python Code '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='approach3_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='challenge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_exm_pic1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_exm_pic2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_exm_pic3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic1',
            field=models.BooleanField(default=False, verbose_name='check Pic 1'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic1_approach2',
            field=models.BooleanField(default=False, verbose_name='Check Pic 1 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic1_approach3',
            field=models.BooleanField(default=False, verbose_name='Check Pic 1'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic2',
            field=models.BooleanField(default=False, verbose_name='check Pic 2'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic2_approach2',
            field=models.BooleanField(default=False, verbose_name='Check Pic 2 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic2_approach3',
            field=models.BooleanField(default=False, verbose_name='Check Pic 2 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic3',
            field=models.BooleanField(default=False, verbose_name='check Pic 3'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic3_approach2',
            field=models.BooleanField(default=False, verbose_name='Check Pic 3 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic3_approach3',
            field=models.BooleanField(default=False, verbose_name='Check Pic 3 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic4',
            field=models.BooleanField(default=False, verbose_name='check Pic 4'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic4_approach2',
            field=models.BooleanField(default=False, verbose_name='Check Pic 4 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic4_approach3',
            field=models.BooleanField(default=False, verbose_name='Check Pic 4 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic5',
            field=models.BooleanField(default=False, verbose_name='check Pic 5'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic5_approach2',
            field=models.BooleanField(default=False, verbose_name='Check Pic 5 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='check_pic5_approach3',
            field=models.BooleanField(default=False, verbose_name='Check Pic 5 '),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='constraints',
            field=models.TextField(blank=True, help_text='After each eg press enter twice to create new constraint', null=True),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='example1_picture',
            field=models.ImageField(blank=True, null=True, upload_to='example1_pictures/'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='example2_picture',
            field=models.ImageField(blank=True, null=True, upload_to='example2_pictures/'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='example3_picture',
            field=models.ImageField(blank=True, null=True, upload_to='example3_pictures/'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='prob_pic',
            field=models.ImageField(blank=True, null=True, upload_to='quesion_pictures'),
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='video_solutions',
            field=models.TextField(blank=True, help_text='After each eg press enter twice to create new video link', null=True),
        ),
        migrations.AlterField(
            model_name='compilerquestion',
            name='const_pic',
            field=models.ImageField(blank=True, null=True, upload_to='constraints_pictures'),
        ),
        migrations.AlterField(
            model_name='compilerquestion',
            name='examples',
            field=models.TextField(blank=True, help_text='After each eg press enter twice to create new example', null=True),
        ),
    ]
