# Generated by Django 5.0 on 2023-12-28 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0006_timetable_week'),
        ('testsManagement', '0022_remove_compilerquestion_hint_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(choices=[('1', 'Week 1'), ('2', 'Week 2'), ('3', 'Week 3'), ('4', 'Week 4'), ('5', 'Week 5'), ('6', 'Week 6'), ('7', 'Week 7'), ('8', 'Week 8')], max_length=1)),
                ('submission_topic', models.CharField(max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissioncourse', to='courseManagement.course')),
            ],
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='course_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsManagement.coursesubmission'),
        ),
    ]
