# Generated by Django 5.0 on 2023-12-30 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0023_coursesubmission_tasksubmission_course_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepracticecode',
            name='compliler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsManagement.compilerquestionloadtemplate'),
        ),
        migrations.AlterField(
            model_name='compilerquestionatempt',
            name='attepmt_number',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compilerquestionatempt',
            name='score',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
    ]
