# Generated by Django 5.0 on 2024-01-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0025_alter_compilerquestionloadtemplate_compiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilerquestionatempt',
            name='submited',
            field=models.BooleanField(default=False),
        ),
    ]
