# Generated by Django 5.0 on 2024-01-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0026_compilerquestionatempt_submited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compilerquestion',
            name='test_case',
        ),
        migrations.AddField(
            model_name='compilerquestion',
            name='test_cases',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
