# Generated by Django 5.0 on 2024-01-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0027_remove_compilerquestion_test_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilerquestionatempt',
            name='code_response_status',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
