# Generated by Django 5.0 on 2024-01-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0009_alter_projecttopic_project_name'),
        ('testsManagement', '0028_compilerquestionatempt_code_response_status'),
        ('userManagement', '0005_student_terms_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.IntegerField()),
                ('score', models.IntegerField()),
                ('correct', models.BooleanField(default=False)),
                ('week', models.IntegerField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_mock_result', to='courseManagement.course')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='com_que', to='testsManagement.compilerquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_for_result_mock', to='userManagement.student')),
            ],
        ),
    ]
