# Generated by Django 5.0 on 2024-01-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0030_savepracticecode_autosave_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilerquestionloadtemplate',
            name='load_template',
            field=models.TextField(blank=True, null=True),
        ),
    ]
