# Generated by Django 4.2.6 on 2024-01-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0007_alter_instructor_rules_regulation_count'),
        ('testsManagement', '0031_alter_compilerquestionloadtemplate_load_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilerquestionatempt',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.instructor'),
        ),
        migrations.AddField(
            model_name='savepracticecode',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.instructor'),
        ),
    ]
