# Generated by Django 4.2.6 on 2024-01-25 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0007_alter_instructor_rules_regulation_count'),
        ('testsManagement', '0032_compilerquestionatempt_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Submitted', max_length=255),
        ),
        migrations.AlterField(
            model_name='compilerquestionatempt',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.student'),
        ),
        migrations.AlterField(
            model_name='savepracticecode',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.student'),
        ),
    ]
