# Generated by Django 4.2.6 on 2024-02-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0033_tasksubmission_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilerquestion',
            name='day',
            field=models.CharField(blank=True, choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3')], max_length=1, null=True),
        ),
    ]
