# Generated by Django 5.0.6 on 2024-06-04 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseManagement', '0013_remove_batch_project_topic_and_more'),
        ('testsManagement', '0037_alter_compilerquestionloadtemplate_compiler_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='course_submission',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='week',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='project_topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.projecttopic'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='submited_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseManagement.projectname'),
        ),
    ]
