# Generated by Django 4.2.6 on 2024-07-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0039_alter_compilerquestionloadtemplate_compiler'),
    ]

    operations = [
        migrations.CreateModel(
            name='JdoodleSupportedLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='language name', max_length=25)),
                ('version_index', models.CharField(help_text='laguage base version', max_length=10)),
            ],
        ),
    ]
