# Generated by Django 4.2.6 on 2024-07-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0040_jdoodlesupportedlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilerquestionloadtemplate',
            name='compiler',
            field=models.CharField(blank=True, choices=[('python3||3', 'python3||3'), ('python3||0', 'python3||0'), ('python3||1', 'python3||1'), ('python3||2', 'python3||2'), ('python3||4', 'python3||4'), ('python3||5', 'python3||5')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jdoodlesupportedlanguage',
            name='version_index',
            field=models.CharField(help_text='language base version', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='jdoodlesupportedlanguage',
            unique_together={('name', 'version_index')},
        ),
    ]
