# Generated by Django 4.2.6 on 2024-09-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsManagement', '0043_questionapproach_questionapproachcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilerquestion',
            name='test_cases_to_pass',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
